// Global Usings

global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using ReLogic.Graphics;
global using SilkyUI.Attributes;
global using SilkyUI.BasicElements;
global using SilkyUI.Extensions;
global using SilkyUI.Graphics2D;
global using SilkyUI.Helper;
global using SilkyUI.Style;
global using System.Reflection;
global using Terraria;
global using Terraria.Audio;
global using Terraria.GameContent;
global using Terraria.GameContent.UI.Elements;
global using Terraria.GameInput;
global using Terraria.ID;
global using Terraria.Localization;
global using Terraria.ModLoader;
global using Terraria.UI;